name: allia_health
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  table_calendar: ^3.2.0
  get: ^4.7.2
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/data/
    - assets/lottie/


  fonts:
    - family: Gelica
      fonts:
        - asset: assets/fonts/gelicia/Gelica-black.otf
          weight: 900
        - asset: assets/fonts/gelicia/Gelica-blackitalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/gelicia/Gelica-bold.otf
          weight: 700
        - asset: assets/fonts/gelicia/Gelica-bolditalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/gelicia/Gelica-extralight.otf
          weight: 200
        - asset: assets/fonts/gelicia/Gelica-extralightitalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/gelicia/Gelica-italic.otf
          style: italic
        - asset: assets/fonts/gelicia/Gelica-light.otf
          weight: 300
        - asset: assets/fonts/gelicia/Gelica-lightitalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/gelicia/Gelica-medium.otf
          weight: 500
        - asset: assets/fonts/gelicia/Gelica-mediumitalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/gelicia/Gelica-regular.otf
          weight: 400
        - asset: assets/fonts/gelicia/Gelica-semibold.otf
          weight: 600
        - asset: assets/fonts/gelicia/Gelica-semibolditalic.otf
          weight: 600
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/lato/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/lato/Lato-ThinItalic.ttf
          weight: 100
          style: italic
